config/routes.rb
Proposta::Application.routes.draw do
  get "welcome/index"

  devise_for :users

  resources :proposals do
    post 'comment'
  end

  

  root :to => 'welcome#index'

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  belongs_to :user
  belongs_to :role
  attr_accessible :role_id, :user_id
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  attr_accessible :provider, :token, :token_secret, :uid, :user_id
  belongs_to :user
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :proposal
  attr_accessible :text, :proposal_id

  validates_presence_of :text
end

app/models/proposal.rb
class Proposal < ActiveRecord::Base
  before_save :ensure_proposal_token

  attr_accessible :description, :title, :token, :user_id
  has_many :comments
  belongs_to :user

  def ensure_proposal_token
    if token.blank?
      self.token = generate_proposal_token
    end
  end
 
  private
  
  def generate_proposal_token
    loop do
      token = Devise.friendly_token
      break token unless Proposal.where(token: token).first
    end
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  attr_accessible :name
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save :ensure_authentication_token
  before_save :ensure_role_proposal

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
  :registerable,
  :omniauthable,
  :recoverable, 
  :rememberable, 
  :trackable
  # :validatable, 
  # :token_authenticatable, 
  # :confirmable,
  # :lockable, 
  # :timeoutable ,
   # :omniauthable

  # attr_accessible :title, :body
  attr_accessible :email, :password, :remember_me, :password_confirmation
  has_many :authentications, :dependent => :destroy

  has_many :assignments
  has_many :roles, :through => :assignments

  has_many :proposals

  validates_presence_of :email
  validates_uniqueness_of :email

  def role_symbols
    roles.map do |role|
      role.name.underscore.to_sym
    end
  end

  def has_role? role
    role_symbols.include?(role)
  end

  def apply_omniauth(omni)
    authentications.build(:provider => omni['provider'],
                          :uid => omni['uid'],
                          :token => omni['credentials'].token,
                          :token_secret => omni['credentials'].secret)

    # password = Devise.friendly_token[0,20] if password.blank?
  end

  def password_required?
    (authentications.empty? || !password.blank?) && super
  end

  def update_with_password(params, *options)
    if encrypted_password.blank?
      update_attributes(params, *options)
    else
      super
    end
  end

  def ensure_authentication_token
    if authentication_token.blank?
      self.authentication_token = generate_authentication_token
    end
  end
 
  def ensure_role_proposal
    role = Role.where(name: 'proposal').first
    if role 
      self.roles << role
    else
      self.roles.build({name: 'proposal'}) 
    end
  end
  private
  
  def generate_authentication_token
    loop do
      token = Devise.friendly_token
      break token unless User.where(authentication_token: token).first
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
   # This is our new function that comes before Devise's one
  before_filter :authenticate_user_from_token!
  # This is Devise's authentication
  # before_filter :authenticate_user!

  before_filter { |c| Authorization.current_user = c.current_user }
 
  private
  
  def authenticate_user_from_token!
    user_email = params[:user_email].presence
    user       = user_email && User.find_by_email(user_email)
 
    # Notice how we use Devise.secure_compare to compare the token
    # in the database with the token given in the params, mitigating
    # timing attacks.
    if user && Devise.secure_compare(user.authentication_token, params[:user_token])
      sign_in user, store: true
    end
  end

  protected

  def permission_denied
    flash[:error] = "Desculpe, você não tem permissão para acessar essa página."
    redirect_to root_url
  end
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
  filter_access_to :all

  # GET /proposals
  # GET /proposals.json
  def index
    @proposals = current_user.proposals

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @proposals }
    end
  end

  # GET /proposals/1
  # GET /proposals/1.json
  def show
    id = params[:id]

    begin
        Float(id)
        if current_user
          @proposal = Proposal.find(id)
          unless current_user.proposals.map {|p| p.id.to_s} .include? id
            redirect_to root_path, :flash => { :error => 'Sem permissão, proposta não é sua.'}
            return
          end
        else
          redirect_to root_path, :flash => { :error => 'Sem permissão'}
          return
        end
        
    rescue ArgumentError, TypeError
      @proposal = Proposal.where(token: id).first
      unless @proposal 
        message = "TOKEN ACCESS inválido."
        redirect_to root_path, :flash => { :error => message}
        return
      end

    rescue Exception => e  
      redirect_to root_path, :flash => { :error => e.message}
      return 
    end

    @comment = Comment.new()
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @proposal }
    end
  end

  # GET /proposals/new
  # GET /proposals/new.json
  def new
    @proposal = Proposal.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @proposal }
    end
  end

  # GET /proposals/1/edit
  def edit
    @proposal = Proposal.find(params[:id])
    unless current_user.proposals.map {|p| p.id.to_s} .include? @proposal.id.to_s
      redirect_to proposal_path, :flash => { :error => 'Sem permissão, proposta não é sua.'}
      return
    end
  end

  # POST /proposals
  # POST /proposals.json
  def create
    @proposal = Proposal.new(params[:proposal])
    @proposal.user = current_user
    respond_to do |format|
      if @proposal.save
        format.html { redirect_to @proposal, notice: 'Proposal was successfully created.' }
        format.json { render json: @proposal, status: :created, location: @proposal }
      else
        format.html { render action: "new" }
        format.json { render json: @proposal.errors, status: :unprocessable_entity }
      end
    end
  end

  def comment
    
    id = params[:proposal_id]

    begin
      Float(id)
      @proposal = Proposal.find(id)
    rescue ArgumentError, TypeError
      @proposal = Proposal.where(token: id).first
      unless @proposal 
        message = "TOKEN ACCESS inválido 2."
        redirect_to root_path, :flash => { :error => message}
        return
      end
    rescue Exception => e  
      redirect_to root_path, :flash => { :error => e.message}
      return 
    end

    @comment = Comment.new(params[:comment])
    @comment.proposal = @proposal

    if @comment.save
      redirect_to :back, notice: '' 
    else
      redirect_to :back, :flash => { :error => "Preencha o corpo do comentário." }
    end
  end

  # PUT /proposals/1
  # PUT /proposals/1.json
  def update
    @proposal = Proposal.find(params[:id])

    unless current_user.proposals.map {|p| p.id.to_s} .include? @proposal.id.to_s
      redirect_to proposal_path, :flash => { :error => 'Sem permissão, proposta não é sua.'}
      return
    end

    respond_to do |format|
      if @proposal.update_attributes(params[:proposal])
        format.html { redirect_to @proposal, notice: 'Proposal was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @proposal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proposals/1
  # DELETE /proposals/1.json
  def destroy
    @proposal = Proposal.find(params[:id])
    unless current_user.proposals.map {|p| p.id.to_s} .include? @proposal.id.to_s
      redirect_to :back, :flash => { :error => 'Sem permissão, proposta não é sua.'}
      return
    end
    @proposal.destroy

    respond_to do |format|
      format.html { redirect_to proposals_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/proposals_helper.rb
module ProposalsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Proposta" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

  </head>
  <body>

    <div class="container-fluid">
      <%= render partial: 'shared/navbar' %>
      <div class="row-fluid">
        
        <div class="span12">
          <%= bootstrap_flash %>
          <%= yield %>

           
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2013</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/proposals/_form.html.erb
<%= form_for @proposal, :html => { :class => 'form-horizontal' , :style => 'text-align: center'} do |f| %>
  <div >
    <%= f.text_field :title, :class => 'text_field' , :placeholder => 'Title' %>
  </div>

  <div >
    <%= f.text_area :description, :class => 'text_area', :placeholder => 'Description', :cols => '500', rows: '10' %>
  </div>

  <div class="form-actions" style="padding-left: 0px;">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                proposals_path, :class => 'btn' %>
                
  </div>
<% end %>

app/views/proposals/edit.html.erb
<%- model_class = Proposal -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/proposals/index.html.erb
<%- model_class = Proposal -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:token) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @proposals.each do |proposal| %>
      <tr>
        <td><%= link_to proposal.id, proposal_path(proposal) %></td>
        <td><%= proposal.title %></td>
        <td><%= proposal.token %></td>
        <td><%= proposal.description %></td>
        <td><%=l proposal.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_proposal_path(proposal), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      proposal_path(proposal),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_proposal_path,
            :class => 'btn btn-primary' %>

app/views/proposals/new.html.erb
<%= render :partial => 'form' %>

app/views/proposals/show.html.erb
<%- model_class = Proposal -%>
<div style='text-align: center'>
<div class="page-header">
  <h1><%= @proposal.title %></h1>
</div>

<dl class="dl-vertical">
  <dd><%= @proposal.description %></dd>
</dl>

<div class="form-actions" style='text-align: center' >
<!-- 
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_proposal_path(@proposal), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              proposal_path(@proposal),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
 -->
  <%= link_to "Aprovar", edit_proposal_path(@proposal), :class => 'btn btn-primary' %>
  <%= link_to "Rejeitar", edit_proposal_path(@proposal), :class => 'btn btn-danger' %>
</div>


</div>

<%= form_for @comment, url: proposal_comment_path(@proposal), :html => { :class => 'form-horizontal' , :style => 'text-align: center'} do |f| %>
  <div >
    <%= f.text_area :text, :class => 'text_area', :placeholder => 'Description', :cols => '200', rows: '3 ' %>
  </div>

  <div style="padding-left: 0px;">
    <%= f.submit "Comentar", :class => 'btn' %>
  </div>
<% end %>


<div id="comentarios" >
  <ol>
  <% @proposal.comments.each do |comment| %>
    <li> <%= comment.text %> </li>
  <% end %>
  </ol>
</div>

app/views/shared/_navbar.html.erb
<%= nav_bar :brand => "Propõe aê", :responsive => true do %>
    <%= menu_group do %>
        <%= menu_item "Propostas", proposals_path %>
    <% end %>
    <%= menu_group :pull => :right do %>
         <% if current_user %>
         <%= menu_item current_user.email , ""%>
            <%= menu_item "Log Out",  destroy_user_session_path, :method => :delete%>
        <% else %>
            <%= menu_item "Log In",  new_user_session_path %>
        <% end %>
    <% end %>


<% end %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>